apiVersion: batch/v1
kind: Job
metadata:
  name: 210-ldap-waitfor-common-services
  annotations:
    argocd.argoproj.io/sync-wave: "210"
  namespace: {{.Values.aiManagerNamespace}}
spec:
  template:
    spec:
      containers:
        - name: config
          image: quay.io/openshift/origin-cli:latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "64Mi"
              cpu: "150m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          command:
            - /bin/sh
            - -c
            - |
              set -x

              while : ; do
                READY=$(oc get pod -n ibm-common-services | grep "1/1\|2/2\|3/3\|4/4"|wc -l|tr -d ' ')
                if [[  $READY  -lt '33' ]]; then
                  echo 'ibm-common-services Deployment not ready yet.'
                  sleep 30
                else
                  break
                fi
              done
          
      serviceAccountName: openshift-argocd-admin-ai
      restartPolicy: Never
  backoffLimit: 4
